require 'minitest/autorun'
require '../lib/nabeatsu'

class NabeatsuTest < Minitest::Test
  def test_go_crazy_if_ver
    assert_equal '1', go_crazy_if_ver(1)
    assert_equal '2', go_crazy_if_ver(2)
    assert_equal '3!', go_crazy_if_ver(3)
    assert_equal '4', go_crazy_if_ver(4)
    assert_equal '5', go_crazy_if_ver(5)
    assert_equal '6!', go_crazy_if_ver(6)
    assert_equal '7', go_crazy_if_ver(7)
    assert_equal '8', go_crazy_if_ver(8)
    assert_equal '9!', go_crazy_if_ver(9)
    assert_equal '10', go_crazy_if_ver(10)
    assert_equal '11', go_crazy_if_ver(11)
    assert_equal '12!', go_crazy_if_ver(12)
    assert_equal '13!', go_crazy_if_ver(13)
    assert_equal '14', go_crazy_if_ver(14)
    assert_equal '15!', go_crazy_if_ver(15)
    assert_equal '16', go_crazy_if_ver(16)
    assert_equal '17', go_crazy_if_ver(17)
    assert_equal '18!', go_crazy_if_ver(18)
    assert_equal '19', go_crazy_if_ver(19)
    assert_equal '20', go_crazy_if_ver(20)
    assert_equal '21!', go_crazy_if_ver(21)
    assert_equal '22', go_crazy_if_ver(22)
    assert_equal '23!', go_crazy_if_ver(23)
    assert_equal '24!', go_crazy_if_ver(24)
    assert_equal '25', go_crazy_if_ver(25)
    assert_equal '26', go_crazy_if_ver(26)
    assert_equal '27!', go_crazy_if_ver(27)
    assert_equal '28', go_crazy_if_ver(28)
    assert_equal '29', go_crazy_if_ver(29)
    assert_equal '30!', go_crazy_if_ver(30)
    assert_equal '31!', go_crazy_if_ver(31)
    assert_equal '32!', go_crazy_if_ver(32)
    assert_equal '33!', go_crazy_if_ver(33)
    assert_equal '34!', go_crazy_if_ver(34)
    assert_equal '35!', go_crazy_if_ver(35)
    assert_equal '36!', go_crazy_if_ver(36)
    assert_equal '37!', go_crazy_if_ver(37)
    assert_equal '38!', go_crazy_if_ver(38)
    assert_equal '39!', go_crazy_if_ver(39)
    assert_equal '40', go_crazy_if_ver(40)
  end

  def test_go_crazy_ternary_ver
    assert_equal '1', go_crazy_ternary_ver(1)
    assert_equal '2', go_crazy_ternary_ver(2)
    assert_equal '3!', go_crazy_ternary_ver(3)
    assert_equal '4', go_crazy_ternary_ver(4)
    assert_equal '5', go_crazy_ternary_ver(5)
    assert_equal '6!', go_crazy_ternary_ver(6)
    assert_equal '7', go_crazy_ternary_ver(7)
    assert_equal '8', go_crazy_ternary_ver(8)
    assert_equal '9!', go_crazy_ternary_ver(9)
    assert_equal '10', go_crazy_ternary_ver(10)
    assert_equal '11', go_crazy_ternary_ver(11)
    assert_equal '12!', go_crazy_ternary_ver(12)
    assert_equal '13!', go_crazy_ternary_ver(13)
    assert_equal '14', go_crazy_ternary_ver(14)
    assert_equal '15!', go_crazy_ternary_ver(15)
    assert_equal '16', go_crazy_ternary_ver(16)
    assert_equal '17', go_crazy_ternary_ver(17)
    assert_equal '18!', go_crazy_ternary_ver(18)
    assert_equal '19', go_crazy_ternary_ver(19)
    assert_equal '20', go_crazy_ternary_ver(20)
    assert_equal '21!', go_crazy_ternary_ver(21)
    assert_equal '22', go_crazy_ternary_ver(22)
    assert_equal '23!', go_crazy_ternary_ver(23)
    assert_equal '24!', go_crazy_ternary_ver(24)
    assert_equal '25', go_crazy_ternary_ver(25)
    assert_equal '26', go_crazy_ternary_ver(26)
    assert_equal '27!', go_crazy_ternary_ver(27)
    assert_equal '28', go_crazy_ternary_ver(28)
    assert_equal '29', go_crazy_ternary_ver(29)
    assert_equal '30!', go_crazy_ternary_ver(30)
    assert_equal '31!', go_crazy_ternary_ver(31)
    assert_equal '32!', go_crazy_ternary_ver(32)
    assert_equal '33!', go_crazy_ternary_ver(33)
    assert_equal '34!', go_crazy_ternary_ver(34)
    assert_equal '35!', go_crazy_ternary_ver(35)
    assert_equal '36!', go_crazy_ternary_ver(36)
    assert_equal '37!', go_crazy_ternary_ver(37)
    assert_equal '38!', go_crazy_ternary_ver(38)
    assert_equal '39!', go_crazy_ternary_ver(39)
    assert_equal '40', go_crazy_ternary_ver(40)
  end
end
